GET https://localhost:5001/api/productos HTTP/1.0
Accept: application/json

GET https://localhost:5001/api/productos/5 HTTP/1.0
Accept: application/json

POST https://localhost:5001/api/productos HTTP/1.0
Content-Type: application/json

{
  "name": "product 10",
  "descripcion": "producto 10",
  "price": 100,
  "imagenName": "image1.jpg",
  "dueDate": "2022-01-01T00:00:00",
  "status": "A"
}

POST https://api.sendgrid.com/v3/mail/send HTTP/1.0
Authorization: Bearer
Content-Type: application/json

{
  "categories": [
    "Verificacion"
  ],
  "from": {
    "email": "renato_cortez@usmp.pe",  
    "name": "Renato " 
  },
  "personalizations": [
    {
      "to": [
        {
          "email": "renato.cortez220@gmail.com",
          "name": "Renato C"
        }
      ],
      "subject": "Prueba"
    }
  ],
  "content": [
    {
      "type": "text/plain",
      "value": "Prueba 3"
    }
  ],  
}